server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    user: postgres
    password: 12345
  jpa:
    hibernate:
      dll-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
