server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kerlyson/ead-config-server-repo
          default-label: main

eureka:
  client:
    serviceUrl:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost